version: 2.1

references:
  make_docs: &make_docs
    run:
      name: Make Documentation
      command: |
        # First run the same pipeline as Read-The-Docs
        # apt-get update && apt-get install -y cmake
        # using: https://hub.docker.com/r/readthedocs/build
        # we need to use py3.7 ot higher becase of an issue with metaclass inheritence
        pyenv global 3.7.3
        python --version
        pip install -r requirements/docs.txt
        pip list
        cd docs
        make -f clean
        make -f html --jobs 2 SPHINXOPTS="-W"

jobs:
  build-Docs:
    docker:
      - image: readthedocs/build:latest
    steps:
      - checkout
      - run:
          command: |
            git submodule update --init --recursive
          name: Init git submodule
      - *make_docs
      - store_artifacts:
          path: docs/build/html/
          destination: html
  test:
    docker:
      - image: "vault.habana.ai/gaudi-docker/1.7.1/ubuntu20.04/habanalabs/pytorch-installer-1.13.0:latest"
        environment:
          HABANA_VISIBLE_DEVICES: all
          OMPI_MCA_btl_vader_single_copy_mechanism: none
     
    steps:
      - checkout
      - run:
         name: habana docker image
         command: |
          # perform all required actions
            echo "##vso[task.setvariable variable=CONTAINER_ID]$(head -1 /proc/self/cgroup|cut -d/ -f3)"
            # install sudo in container
            sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
            sudo pip list
            sudo pip uninstall -y lightning pytorch-lightning
            sudo pip list
 #     - run:
 #         name: Run tests
 #         command: |
 #           python -m pytest --cov-report xml --cov-report term --cov .

      
workflows:
  test:
    jobs:
      - build-Docs
