version: 2.1

references:
  make_docs: &make_docs
    run:
      name: Make Documentation
      command: |
        # First run the same pipeline as Read-The-Docs
        # apt-get update && apt-get install -y cmake
        # using: https://hub.docker.com/r/readthedocs/build
        # we need to use py3.7 ot higher becase of an issue with metaclass inheritence
        pyenv global 3.7.3
        python --version
        pip install -r requirements/docs.txt
        pip list
        cd docs
        make -f clean
        make -f html --jobs 2 SPHINXOPTS="-W"

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
  build-Docs:
    docker:
      - image: readthedocs/build:latest
    steps:
      - checkout
      - run:
          command: |
            git submodule update --init --recursive
          name: Init git submodule
      - *make_docs
      - store_artifacts:
          path: docs/build/html/
          destination: html
  hpu-test:
    docker:
      - image: "vault.habana.ai/gaudi-docker/1.8.0/ubuntu20.04/habanalabs/pytorch-installer-1.13.1:latest"
        environment:
          HABANA_VISIBLE_DEVICES: all
          OMPI_MCA_btl_vader_single_copy_mechanism: none
     
    steps:
      - checkout
      - run:
         name: habana docker image
         command: |
          # perform all required actions
            echo "##vso[task.setvariable variable=CONTAINER_ID]$(head -1 /proc/self/cgroup|cut -d/ -f3)"
            # install sudo in container
            sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
            export PACKAGE_NAME="pytorch"
            export FREEZE_REQUIREMENTS="1"
            export PYTHONPATH="${PYTHONPATH}:$(pwd)"
            sudo pip list
            sudo pip uninstall -y lightning pytorch-lightning
            pip install -q -r .actions/requirements.txt
            python .actions/assistant.py requirements_prune_pkgs "--packages=[torch,torchvision]"
            pip install ".[extra,test]"
            pip install -q -r .actions/requirements.txt
            python .actions/assistant.py copy_replace_imports --source_dir="./tests/tests_pytorch" \
            --source_import="lightning.fabric,lightning.pytorch" \
            --target_import="lightning_fabric,pytorch_lightning"
            python .actions/assistant.py copy_replace_imports --source_dir="./examples/pl_hpu" \
            --source_import="lightning.fabric,lightning.pytorch" \
            --target_import="lightning_fabric,pytorch_lightning"
            pip list
            # python -m pytest -sv accelerators/test_hpu.py --forked --junitxml=hpu1_test-results.xml
            python "examples/pl_hpu/mnist_sample.py"
 #     - run:
 #         name: Run tests
 #         command: |
 #           python -m pytest --cov-report xml --cov-report term --cov .

      
workflows:
  test:
    jobs:
      - build-and-test
      #- build-Docs
      #- hpu-test
